name: build-base-container

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  REGISTRY: ghcr.io

jobs:
  lint:
    name: Python Black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Python Black
      uses: cytopia/docker-black@0.8
      with:
        path: src/
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.0.2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true   # Will only build if this is not here
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:base
